version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - pgsql_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgsql_data: {}